template header
ruleid
ifcondition
package com.chengdu.jiq.drools1
import fk.sp.seldon.msku.MSKU
import com.chengdu.jiq.model.bo.UserDataModel;
import com.chengdu.jiq.model.bo.RuleCheckResult;
global java.util.List awardList
template "tmp1"
rule "@{ruleid}"
    when
        userData : UserDataModel(@{ifcondition})
    then
        awardList.addAll(awards);
        System.out.println("规则中打印日志：校验通过!");
end
end template