package com.chengdu.jiq.drools1
import com.chengdu.jiq.model.bo.UserDataModel;
import com.chengdu.jiq.service.rules.RuleService;
import java.util.Map;
global RuleService ruleService;

rule "Calculate Variance"
when
    $data : UserDataModel();
    UserDataModel(context["investAmount"] > 1000);
    UserDataModel(context["firstInvest"] == true);
    Map(this["investTotalCount"] > 1000) from ruleService.initConditionData2($data, "investTotalCount");
then
    // the variance of the test scores is $v
    System.out.println("规则中打印日志：校验通过44444444!");
end